apiVersion: apps/v1
kind: Deployment
metadata: 
    name: ORMAE-mongodb-Deployment
    labels:
        app: mongodb
spec:
    replicas: 3
    selector:
        matchlabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
            - name: mongodb
              image: mongo
              ports:
              - conainerport: 27017
              env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: ORMAE-mongodb-secret
                        key: mongo-root-username
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: ORMAE-mongodb-secret
                        key: mongo-root-password
---
# mongodb internal service or internal api
apiversion: v1
kind: Service
metadata:
    name: ORMAE-mongodb-service
spec:
    selector:
        app: mongodb
    ports:
        - protocol: tcp
          port: 27017
          targetport: 27017 

    